### ISSUE TITLE
Not Related to this lib 

### ISSUE THREAD

**Issue by PrashantKT** [JacobHearst/ScryfallKit#18]
Hi

I was using your lib GCDWebserver using SPM but I think you have deleted it ? 

Could you pl share the lib so I can continue using it or anyother way to use this 

Thanks

**Comment by JacobHearst** [comment]
Hi @PrashantKT I just forked GCDWebServer to make it a Swift Package (if memory serves me right). It's quite simple to do so yourself if you'd like. [Here are docs on how to fork a repository](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo) (in this case [the original GCDWebServer](https://github.com/swisspol/GCDWebServer)). Then you can clone the repo locally and make a Swift Package. There's documentation on that step [here](https://www.swift.org/packages/#create-your-own).
