### ISSUE TITLE
`art_crop` and `border_crop` URIs Missing from Cards

### ISSUE THREAD

**Issue by Bonney** [JacobHearst/ScryfallKit#21]
Hello! I am having an issue where `Card` objects returned from the API are missing the `art_crop` and `border_crop` image URI. All other sizes return proper URLs. See attached photo.

My guess is this is a Codable issue, although your code appears to have the proper coding keys set in the ImageUris struct.

As a test I have confirmed the direct Scryfall API returns URLs for both art and border crops that are valid, and will successfully load in a SwiftUI AsyncImage.

<img width="1195" alt="Screenshot 2024-05-14 at 11 47 26 AM" src="https://github.com/JacobHearst/ScryfallKit/assets/3890339/3c82e981-b4cb-4e82-838c-16eacef2359a">

**Comment by Bonney** [comment]
I actually believe I found the issue, after poking around a bit more it appears the custom coding keys are redundant and causing the issue; see my PR: https://github.com/JacobHearst/ScryfallKit/pull/22

**Comment by juliussohn** [comment]
Hey I still have this problem when searching for cards. Th borderCrop and artCrop are returned as nil
