### ISSUE TITLE
Request for New Release for Xcode 16 and Swift 6 Support

### ISSUE THREAD

**Issue by missingems** [JacobHearst/ScryfallKit#24]
Hi,

Since Xcode 16 is coming next week, can we get a new release with Sendable changes for Swift 6?

Thanks!

**Comment by JacobHearst** [comment]
v5.11.0 is [now available!](https://github.com/JacobHearst/ScryfallKit/releases/tag/v5.11.0)

**Comment by missingems** [comment]
> v5.11.0 is [now available!](https://github.com/JacobHearst/ScryfallKit/releases/tag/v5.11.0)

Thanks
